version: "3"
services:
  angular-todo:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-sandbox
    volumes:
      - ./:/usr/src/app/app-ui
      - /usr/src/app/app-ui/node_modules
